<a href="https://colab.research.google.com/github/FavourAkinwande/Principlecomponent_Analysis/blob/main/Formative_Assignment_PCA_%5BFavour_Akinwande%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



<center>
    <img src="https://miro.medium.com/v2/resize:fit:300/1*mgncZaKaVx9U6OCQu_m8Bg.jpeg">
</center>



The goal of PCA is to extract information while reducing the number of features
from a dataset by identifying which existing features relate to another. The crux of the algorithm is trying to determine the relationship between existing features, called principal components, and then quantifying how relevant these principal components are. The principal components are used to transform the high dimensional data to a lower dimensional data while preserving as much information. For a principal component to be relevant, it needs to capture information about the features. We can determine the relationships between features using covariance.

In [4]:
#Import necessary package
import numpy as np

In [7]:

data = np.array([
    [   1,   2,  -1,   4,  10],
    [   3,  -3,  -3,  12, -15],
    [   2,   1,  -2,   4,   5],
    [   5,   1,  -5,  10,   5],
    [   2,   3,  -3,   5,  12],
    [   4,   0,  -3,  16,   2],
])

### Step 1: Standardize the Data along the Features

![image.png](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxe5VYCBsaZddkkTZlCY24Yov4JJD4-ArTA&usqp=CAU)




Explain why we need to handle the data on the same scale.

**[TO DO: Insert Answer here]**

In [8]:
standardized_data = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
print(standardized_data)

[[-1.36438208  0.70710678  1.5109662  -0.99186978  0.77802924]
 [ 0.12403473 -1.94454365 -0.13736056  0.77145428 -2.06841919]
 [-0.62017367  0.1767767   0.68680282 -0.99186978  0.20873955]
 [ 1.61245155  0.1767767  -1.78568733  0.33062326  0.20873955]
 [-0.62017367  1.23743687 -0.13736056 -0.77145428  1.00574511]
 [ 0.86824314 -0.35355339 -0.13736056  1.65311631 -0.13283426]]


![cov matrix.webp](https://dmitry.ai/uploads/default/original/1X/9bd2851674ebb55e404cc3ff5e2ffe65b42ff460.png)

We use the pair - wise covariance of the different features to determine how they relate to each other. With these covariances, our goal is to group / cluster based on similar patterns. Intuitively, we can relate features if they have similar covariances with other features.

### Step 2: Calculate the Covariance Matrix



In [9]:
cov_matrix = np.cov(standardized_data, ddof=0, rowvar=False)
#Print Covariance matrix
print(cov_matrix)

[[ 1.         -0.35082321 -0.9029865   0.75182742 -0.30833773]
 [-0.35082321  1.          0.16997503 -0.64291136  0.98959863]
 [-0.9029865   0.16997503  1.         -0.49956057  0.18506849]
 [ 0.75182742 -0.64291136 -0.49956057  1.         -0.58348328]
 [-0.30833773  0.98959863  0.18506849 -0.58348328  1.        ]]


### Step 3: Eigendecomposition on the Covariance Matrix


In [10]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [3.17488134e+00 1.44713013e+00 4.12109190e-02 3.95157890e-05
 3.36738100e-01]
Eigenvectors:
 [[-0.4640131   0.45182808 -0.70733581  0.28128049 -0.03317471]
 [ 0.45019005  0.48800851  0.29051532  0.6706731  -0.15803498]
 [ 0.37929082 -0.55665017 -0.48462321  0.24186072 -0.5029143 ]
 [-0.4976889   0.03162214  0.36999674 -0.03373724 -0.78311558]
 [ 0.43642295  0.49682965 -0.20861365 -0.64143906 -0.32822489]]


### Step 4: Sort the Principal Components
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

In [12]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

order_of_importance = np.argsort(eigenvalues)[::-1]
print ( 'The order of importance is :\n {}'.format(order_of_importance))

# utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[order_of_importance]

print('\n\n Sorted eigen values:\n{}'.format(sorted_eigenvalues))
sorted_eigenvectors = eigenvectors[order_of_importance] # sort the columns
print('\n\n The sorted eigen vector matrix is: \n {}'.format(sorted_eigenvectors))

The order of importance is :
 [0 1 4 2 3]


 Sorted eigen values:
[3.17488134e+00 1.44713013e+00 3.36738100e-01 4.12109190e-02
 3.95157890e-05]


 The sorted eigen vector matrix is: 
 [[-0.4640131   0.45182808 -0.70733581  0.28128049 -0.03317471]
 [ 0.45019005  0.48800851  0.29051532  0.6706731  -0.15803498]
 [ 0.43642295  0.49682965 -0.20861365 -0.64143906 -0.32822489]
 [ 0.37929082 -0.55665017 -0.48462321  0.24186072 -0.5029143 ]
 [-0.4976889   0.03162214  0.36999674 -0.03373724 -0.78311558]]


Question:

1. Why do we order eigen values and eigen vectors?

- This is because eigenvectors constitute the principal components in a PCA and thus the most important ones will have higher eigenvalues. Thus, ordering them is important so that we tend to proritize the most significant components and their associated eigenvalues as this will make the PCA process much more easier.
2. Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

- No, it is not true. In PCA, we consider the highest eigenvalues because they correspond to the most significant principal components. These principal components capture more variance in the data, making them more informative and essential for understanding the underlying structure of the dataset. The higher eigenvalues are associated with directions in the feature space where the data varies the most, thus containing the most critical information we need to focus on.


You want to see what percentage of information each eigen value holds. You would have print out the percentage of each eigen value using the formula



> (sorted eigen values / sum of all sorted eigen values) * 100



In [ ]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

explained_variance = sorted_eigenvalues / np.sum(sorted_eigenvalues) * 100
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print( explained_variance)

['63.50%', '28.94%', '6.73%', '0.82%', '0.00%']


#Initialize the number of Principle components then perfrom matrix multiplication with the variable K example k = 3 for 3 priciple components




> The reulting matrix (with reduced data) = standardized data * vector with columns k

See expected output for k = 2



In [13]:
# select the number of principal components
k = 2

#reduced_data = #TO DO: Insert code here
reduced_data = np.matmul(data, sorted_eigenvectors)[:, :k] # transform the original data

In [14]:
print(reduced_data)

[[-3.45978171 -0.97936381]
 [ 7.96494502 -8.7531645 ]
 [-2.3219633  -1.67048461]
 [-2.74752656 -5.14539038]
 [-4.96253765 -1.52659242]
 [ 1.907954   -8.52633514]]


In [15]:
print(reduced_data.shape)

(6, 2)


# *What are 2 positive effects and 2 negative effects of PCA

Give 2 Benefits and 2 limitations

**BENEFITS**

1) Dimensionality Reduction: PCA can significantly reduce the dimensionality of a dataset by projecting the data onto a lower-dimensional subspace while retaining most of the important information or variance present in the original data. This can lead to faster computation times, improved model performance, and better data visualization.

2) Noise Reduction: PCA can help in separating the signal (important information) from the noise (irrelevant or redundant information) in the data. By retaining only the principal components that capture the most variance, PCA effectively filters out noise and redundant information, leading to a more robust and interpretable representation of the data.

**LIMITATIONS**

1) Loss of Information: While PCA aims to retain most of the important information in the data, some information is inevitably lost during the dimensionality reduction process. The principal components are linear combinations of the original features, and any non-linear relationships or structures in the data may not be captured adequately.

2) Interpretation Challenges: The principal components obtained from PCA are often difficult to interpret, as they are combinations of the original features. Understanding the meaning or significance of each principal component can be challenging, especially in high-dimensional datasets with many features. This can make it difficult to derive insights or communicate the results to stakeholders.



Additional Requirements: Using Dataset Provided


In [17]:
#Import Packages
import pandas as pd
import numpy as np

In [19]:
from google.colab import drive
drive.mount('/content/drive')


# Loading the dataset from the specific path
file_path = '/content/drive/My Drive/Colab Notebooks/fuel_econ.csv'
df = pd.read_csv(file_path)

# Displayed first few rows of the dataframe
df.head(10)

Mounted at /content/drive


id        make           model  year           VClass  \
0  32204      Nissan            GT-R  2013  Subcompact Cars   
1  32205  Volkswagen              CC  2013     Compact Cars   
2  32206  Volkswagen              CC  2013     Compact Cars   
3  32207  Volkswagen      CC 4motion  2013     Compact Cars   
4  32208   Chevrolet  Malibu eAssist  2013     Midsize Cars   
5  32209       Lexus          GS 350  2013     Midsize Cars   
6  32210       Lexus      GS 350 AWD  2013     Midsize Cars   
7  32214     Hyundai   Genesis Coupe  2013  Subcompact Cars   
8  32215     Hyundai   Genesis Coupe  2013  Subcompact Cars   
9  32216     Hyundai   Genesis Coupe  2013  Subcompact Cars   

               drive              trans          fuelType  cylinders  displ  \
0    All-Wheel Drive    Automatic (AM6)  Premium Gasoline          6    3.8   
1  Front-Wheel Drive  Automatic (AM-S6)  Premium Gasoline          4    2.0   
2  Front-Wheel Drive     Automatic (S6)  Premium Gasoline          6    3.6   
3    All-Wheel Drive     Automatic (S6)  Premium Gasoline          6    3.6   
4  Front-Wheel Drive     Automatic (S6)  Regular Gasoline          4    2.4   
5   Rear-Wheel Drive     Automatic (S6)  Premium Gasoline          6    3.5   
6    All-Wheel Drive     Automatic (S6)  Premium Gasoline          6    3.5   
7   Rear-Wheel Drive    Automatic 8-spd  Premium Gasoline          4    2.0   
8   Rear-Wheel Drive       Manual 6-spd  Premium Gasoline          4    2.0   
9   Rear-Wheel Drive    Automatic 8-spd  Premium Gasoline          6    3.8   

   pv2  pv4     city    UCity  highway  UHighway     comb  co2  feScore  \
0   79    0  16.4596  20.2988  22.5568   30.1798  18.7389  471        4   
1   94    0  21.8706  26.9770  31.0367   42.4936  25.2227  349        6   
2   94    0  17.4935  21.2000  26.5716   35.1000  20.6716  429        5   
3   94    0  16.9415  20.5000  25.2190   33.5000  19.8774  446        5   
4    0   95  24.7726  31.9796  35.5340   51.8816  28.6813  310        8   
5    0   99  19.4325  24.1499  28.2234   38.5000  22.6002  393        6   
6    0   99  18.5752  23.5261  26.3573   36.2109  21.4213  412        5   
7   89    0  17.4460  21.7946  26.6295   37.6731  20.6507  432        5   
8   89    0  20.6741  26.2000  29.2741   41.8000  23.8235  375        6   
9   89    0  16.4675  20.4839  24.5605   34.4972  19.3344  461        4   

   ghgScore  
0         4  
1         6  
2         5  
3         5  
4         8  
5         6  
6         5  
7         5  
8         6  
9         4

In [32]:
# Select only numeric columns
numeric_df = df.select_dtypes(include=[np.number])
numeric_df.head()


id  year  cylinders  displ  pv2  pv4     city    UCity  highway  \
0  32204  2013          6    3.8   79    0  16.4596  20.2988  22.5568   
1  32205  2013          4    2.0   94    0  21.8706  26.9770  31.0367   
2  32206  2013          6    3.6   94    0  17.4935  21.2000  26.5716   
3  32207  2013          6    3.6   94    0  16.9415  20.5000  25.2190   
4  32208  2013          4    2.4    0   95  24.7726  31.9796  35.5340   

   UHighway     comb  co2  feScore  ghgScore  
0   30.1798  18.7389  471        4         4  
1   42.4936  25.2227  349        6         6  
2   35.1000  20.6716  429        5         5  
3   33.5000  19.8774  446        5         5  
4   51.8816  28.6813  310        8         8

In [31]:


# Standardizing the numeric data
standardized_data = (numeric_df - np.mean(numeric_df, axis=0)) / np.std(numeric_df, axis=0)

# Convert the standardized DataFrame to a NumPy array
standardized_array = standardized_data.to_numpy()

# Print the first five rows as an array
print(standardized_array[:5])


[[-1.73714048 -1.47583548  0.28310163  0.65053594  1.46709627 -1.21737766
  -0.85996012 -0.85242986 -1.29062982 -1.39247459 -1.00832279  1.02283829
  -0.95057953 -0.94575548]
 [-1.73668367 -1.47583548 -0.78181585 -0.72799833  1.86476224 -1.21737766
   0.00642675 -0.11743408  0.18494654 -0.03920038  0.07186379 -0.29854998
   0.1886082   0.1942578 ]
 [-1.73622685 -1.47583548  0.28310163  0.49736547  1.86476224 -1.21737766
  -0.69441634 -0.75324472 -0.5920197  -0.85174957 -0.68633929  0.56793413
  -0.38098566 -0.37574884]
 [-1.73577004 -1.47583548  0.28310163  0.49736547  1.86476224 -1.21737766
  -0.78280029 -0.830286   -0.82738386 -1.02758796 -0.81865124  0.752062
  -0.38098566 -0.37574884]
 [-1.73531322 -1.47583548 -0.78181585 -0.42165738 -0.62727784  0.73489021
   0.47108294  0.43314691  0.96751585  0.99253135  0.64805881 -0.72096098
   1.32779592  1.33427108]]


In [38]:
# Calculating the covariance of the standardized data
cov_matrix = np.cov(standardized_array, ddof=0, rowvar=False)


In [36]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [8.95492947e+00 2.06725328e+00 1.59323656e+00 6.70416990e-01
 3.01607334e-01 1.60976566e-01 1.25518516e-01 6.40042264e-02
 3.23446619e-02 1.36927574e-02 9.24391778e-03 4.24529707e-03
 2.14303627e-03 3.87387264e-04]
Eigenvectors:
 [[ 1.89952516e-02 -6.87675276e-01  7.65365183e-02  1.83729680e-02
  -1.42115022e-02  7.02789695e-02  1.14861126e-01  4.01097554e-03
  -1.15143583e-01 -6.95538857e-01 -6.83326435e-02  2.10633586e-02
  -7.10578367e-03  6.07618642e-04]
 [ 1.24694065e-02 -6.89503292e-01  6.88439505e-02 -9.43831862e-03
  -1.35600088e-02  3.37955333e-02  8.53170135e-02 -7.51768613e-03
  -5.48830131e-02  7.10425085e-01  5.58369479e-02 -9.48384475e-03
  -3.26885432e-04 -3.98397374e-03]
 [-2.81632694e-01  1.98550575e-02  5.61398643e-02  6.00933196e-01
   9.71151716e-02 -7.09369930e-02  2.53817629e-01 -6.79764243e-01
   1.19688616e-01  2.20121563e-03  1.99493288e-02  1.60174402e-02
   8.04028190e-03 -8.90395340e-04]
 [-2.86142593e-01  3.10582044e-02  6.39803619e-02  5.6900

In [37]:
# np.argsort can only provide lowest to highest; use [::-1] to reverse the list

order_of_importance = np.argsort(eigenvalues)[::-1]
print ( 'The order of importance is :\n {}'.format(order_of_importance))

# utilize the sort order to sort eigenvalues and eigenvectors
sorted_eigenvalues = eigenvalues[order_of_importance]

print('\n\n Sorted eigen values:\n{}'.format(sorted_eigenvalues))
sorted_eigenvectors = eigenvectors[order_of_importance] # sort the columns
print('\n\n The sorted eigen vector matrix is: \n {}'.format(sorted_eigenvectors))

The order of importance is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


 Sorted eigen values:
[8.95492947e+00 2.06725328e+00 1.59323656e+00 6.70416990e-01
 3.01607334e-01 1.60976566e-01 1.25518516e-01 6.40042264e-02
 3.23446619e-02 1.36927574e-02 9.24391778e-03 4.24529707e-03
 2.14303627e-03 3.87387264e-04]


 The sorted eigen vector matrix is: 
 [[ 1.89952516e-02 -6.87675276e-01  7.65365183e-02  1.83729680e-02
  -1.42115022e-02  7.02789695e-02  1.14861126e-01  4.01097554e-03
  -1.15143583e-01 -6.95538857e-01 -6.83326435e-02  2.10633586e-02
  -7.10578367e-03  6.07618642e-04]
 [ 1.24694065e-02 -6.89503292e-01  6.88439505e-02 -9.43831862e-03
  -1.35600088e-02  3.37955333e-02  8.53170135e-02 -7.51768613e-03
  -5.48830131e-02  7.10425085e-01  5.58369479e-02 -9.48384475e-03
  -3.26885432e-04 -3.98397374e-03]
 [-2.81632694e-01  1.98550575e-02  5.61398643e-02  6.00933196e-01
   9.71151716e-02 -7.09369930e-02  2.53817629e-01 -6.79764243e-01
   1.19688616e-01  2.20121563e-03  1.99493288e-02

Question:
Why do we order eigen values and eigen vectors?

This is because eigenvectors constitute the principal components in a PCA and thus the most important ones will have higher eigenvalues. Thus, ordering them is important so that we tend to proritize the most significant components and their associated eigenvalues as this will make the PCA process much more easier.

Is it true we would consider the lowest eigen value compared to the highest? Defend your answer

No, it is not true. In PCA, we consider the highest eigenvalues because they correspond to the most significant principal components. These principal components capture more variance in the data, making them more informative and essential for understanding the underlying structure of the dataset. The higher eigenvalues are associated with directions in the feature space where the data varies the most, thus containing the most critical information we need to focus on.


In [39]:
# use sorted_eigenvalues to ensure the explained variances correspond to the eigenvectors

explained_variance = sorted_eigenvalues / np.sum(sorted_eigenvalues) * 100
explained_variance =["{:.2f}%".format(value) for value in explained_variance]
print( explained_variance)

['63.96%', '14.77%', '11.38%', '4.79%', '2.15%', '1.15%', '0.90%', '0.46%', '0.23%', '0.10%', '0.07%', '0.03%', '0.02%', '0.00%']


In [44]:
# select the number of principal components
k = 2

#reduced_data = #TO DO: Insert code here
reduced_data = np.matmul(standardized_array, sorted_eigenvectors)[:, :k]
print(reduced_data)

[[-3.19146207  1.98769416]
 [ 0.38752701  1.99194578]
 [-2.09148498  2.03743394]
 ...
 [ 6.84833724 -2.12577829]
 [-0.99151331 -2.51764543]
 [-1.99449758 -2.60766847]]


In [46]:
print(reduced_data.shape)

(3929, 2)


Benefitsof PCA:

Reduces Dimensionality: PCA can reduce the number of features in a dataset while retaining the most important variance, making the dataset smaller and easier to work with. This reduces the complexity of machine learning models, speeds up training, and can prevent the curse of dimensionality, which often causes poor model performance when there are too many features.

Improves Interpretability: By reducing the dataset to a smaller set of uncorrelated principal components, PCA can reveal the underlying structure of the data. This can make it easier to interpret and visualize relationships between data points.

Limitations of PCA:

Loss of Interpretability: While PCA simplifies data by transforming it into a set of principal components, the new components are often difficult to interpret in terms of the original variables. This makes it harder to understand what each principal component represents in real-world terms.

Risk of Information Loss:  PCA removes the least important components (those with lower variance), but these components can sometimes contain useful information. Especially if too many components are discarded, there’s a risk of losing relevant details, which can negatively impact the model's accuracy.

